# stage1 - build react app first
FROM node:lts-alpine3.9 as build

WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY ./package.json yarn.lock /app/
RUN yarn --silent
COPY . /app
RUN rm -rf node_modules
RUN yarn
RUN yarn build

# stage 2 - build the final image and copy the react build files
FROM nginx:alpine

COPY --from=build /app/build /usr/share/nginx/html
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx/nginx.conf /etc/nginx/conf.d
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
