version: '3'
services:
  app:
    container_name: app
    ports:
      - '7000:7000'
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgres://postgres:test@db.local:5432/auth-proxy
      - PORT=7000
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - db
    links:
      - db:db.local
  db:
    image: postgres:11.5
    volumes:
      - ./.postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=test
      - POSTGRES_USER=postgres
      - POSTGRES_DB=auth-proxy
    volumes:
      - ./scripts:/scripts
    healthcheck:
      test: ["CMD", "/scripts/wait-for-db.sh"]
      interval: 5s
      retries: 5
      timeout: 20s
 