version: '3'
services:
  db:
    image: postgres:11.5
    volumes:
      - ./.postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=test
      - POSTGRES_USER=postgres
      - POSTGRES_DB=auth-proxy
    volumes:
      - ./scripts:/scripts
    healthcheck:
      test: ["CMD", "/scripts/wait-for-db.sh"]
      interval: 5s
      retries: 5
      timeout: 20s