# stage1 - build react app first
FROM node:lts-alpine3.9 as build

WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY ./package.json yarn.lock /app/
RUN yarn --silent
COPY . /app
RUN rm -rf node_modules
RUN yarn
RUN yarn build

RUN yarn start:prod
